###

### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "bor3i@gmail.com",
  "password": "5555",
  "username": "Bor3i"
}

###


### Authenticate
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "bor3i@gmail.com",
  "password": "5555"
}
###

### Create Task
POST http://localhost:8080/api/tasks
Authorization: Bearer <token>
Content-Type: application/json

{
  "title": "Finish project",
  "description": "Complete the API by Friday",
  "isCompleted": false,
  "priority": "LOW",
  "dueDate": "2025-08-08T17:00:00",
  "assignedId": null
}
###

### Get All Tasks
GET http://localhost:8080/api/tasks
Authorization: Bearer <token>
###


### Get Task By ID
GET http://localhost:8080/api/tasks/1
Authorization: Bearer <token>

###

### Delete Task
DELETE http://localhost:8080/api/tasks/1
Authorization: Bearer <token>
###

### Status
GET http://localhost:8080/api/status

###

### Get All Users
GET http://localhost:8080/user
Authorization: Bearer <token>
###
